package august.dao;

import august.entity.Line;
import java.util.List;

public interface LineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated
     */
    int insert(Line record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated
     */
    Line selectByPrimaryKey(String lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated
     */
    List<Line> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Line record);
}