package august.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbg.generated
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_sex
     *
     * @mbg.generated
     */
    private String adminSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_status
     *
     * @mbg.generated
     */
    private Integer adminStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_locationcity
     *
     * @mbg.generated
     */
    private String adminLocationcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_site
     *
     * @mbg.generated
     */
    private String adminSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_password
     *
     * @mbg.generated
     */
    private String adminPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_phone
     *
     * @mbg.generated
     */
    private String adminPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_remark
     *
     * @mbg.generated
     */
    private String adminRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbg.generated
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param adminId the value for admin.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_name
     *
     * @param adminName the value for admin.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_sex
     *
     * @return the value of admin.admin_sex
     *
     * @mbg.generated
     */
    public String getAdminSex() {
        return adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_sex
     *
     * @param adminSex the value for admin.admin_sex
     *
     * @mbg.generated
     */
    public void setAdminSex(String adminSex) {
        this.adminSex = adminSex == null ? null : adminSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_id
     *
     * @return the value of admin.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_id
     *
     * @param userId the value for admin.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_status
     *
     * @return the value of admin.admin_status
     *
     * @mbg.generated
     */
    public Integer getAdminStatus() {
        return adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_status
     *
     * @param adminStatus the value for admin.admin_status
     *
     * @mbg.generated
     */
    public void setAdminStatus(Integer adminStatus) {
        this.adminStatus = adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_locationcity
     *
     * @return the value of admin.admin_locationcity
     *
     * @mbg.generated
     */
    public String getAdminLocationcity() {
        return adminLocationcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_locationcity
     *
     * @param adminLocationcity the value for admin.admin_locationcity
     *
     * @mbg.generated
     */
    public void setAdminLocationcity(String adminLocationcity) {
        this.adminLocationcity = adminLocationcity == null ? null : adminLocationcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_site
     *
     * @return the value of admin.admin_site
     *
     * @mbg.generated
     */
    public String getAdminSite() {
        return adminSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_site
     *
     * @param adminSite the value for admin.admin_site
     *
     * @mbg.generated
     */
    public void setAdminSite(String adminSite) {
        this.adminSite = adminSite == null ? null : adminSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_password
     *
     * @return the value of admin.admin_password
     *
     * @mbg.generated
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_password
     *
     * @param adminPassword the value for admin.admin_password
     *
     * @mbg.generated
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_phone
     *
     * @return the value of admin.admin_phone
     *
     * @mbg.generated
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_phone
     *
     * @param adminPhone the value for admin.admin_phone
     *
     * @mbg.generated
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_remark
     *
     * @return the value of admin.admin_remark
     *
     * @mbg.generated
     */
    public String getAdminRemark() {
        return adminRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_remark
     *
     * @param adminRemark the value for admin.admin_remark
     *
     * @mbg.generated
     */
    public void setAdminRemark(String adminRemark) {
        this.adminRemark = adminRemark == null ? null : adminRemark.trim();
    }
}