package august.entity;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_name
     *
     * @mbg.generated
     */
    private String carName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.placeoforigin
     *
     * @mbg.generated
     */
    private String placeoforigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.line_id
     *
     * @mbg.generated
     */
    private String lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_productiondate
     *
     * @mbg.generated
     */
    private Date carProductiondate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_bugdate
     *
     * @mbg.generated
     */
    private Date carBugdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_remark
     *
     * @mbg.generated
     */
    private String carRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_id
     *
     * @return the value of car.car_id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_id
     *
     * @param carId the value for car.car_id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_name
     *
     * @return the value of car.car_name
     *
     * @mbg.generated
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_name
     *
     * @param carName the value for car.car_name
     *
     * @mbg.generated
     */
    public void setCarName(String carName) {
        this.carName = carName == null ? null : carName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.placeoforigin
     *
     * @return the value of car.placeoforigin
     *
     * @mbg.generated
     */
    public String getPlaceoforigin() {
        return placeoforigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.placeoforigin
     *
     * @param placeoforigin the value for car.placeoforigin
     *
     * @mbg.generated
     */
    public void setPlaceoforigin(String placeoforigin) {
        this.placeoforigin = placeoforigin == null ? null : placeoforigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.line_id
     *
     * @return the value of car.line_id
     *
     * @mbg.generated
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.line_id
     *
     * @param lineId the value for car.line_id
     *
     * @mbg.generated
     */
    public void setLineId(String lineId) {
        this.lineId = lineId == null ? null : lineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_productiondate
     *
     * @return the value of car.car_productiondate
     *
     * @mbg.generated
     */
    public Date getCarProductiondate() {
        return carProductiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_productiondate
     *
     * @param carProductiondate the value for car.car_productiondate
     *
     * @mbg.generated
     */
    public void setCarProductiondate(Date carProductiondate) {
        this.carProductiondate = carProductiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_bugdate
     *
     * @return the value of car.car_bugdate
     *
     * @mbg.generated
     */
    public Date getCarBugdate() {
        return carBugdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_bugdate
     *
     * @param carBugdate the value for car.car_bugdate
     *
     * @mbg.generated
     */
    public void setCarBugdate(Date carBugdate) {
        this.carBugdate = carBugdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_remark
     *
     * @return the value of car.car_remark
     *
     * @mbg.generated
     */
    public String getCarRemark() {
        return carRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_remark
     *
     * @param carRemark the value for car.car_remark
     *
     * @mbg.generated
     */
    public void setCarRemark(String carRemark) {
        this.carRemark = carRemark == null ? null : carRemark.trim();
    }
}