package august.entity;

public class Cityarea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.cityArea_id
     *
     * @mbg.generated
     */
    private String cityareaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.cityArea_name
     *
     * @mbg.generated
     */
    private String cityareaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.cityArea_id
     *
     * @return the value of cityarea.cityArea_id
     *
     * @mbg.generated
     */
    public String getCityareaId() {
        return cityareaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.cityArea_id
     *
     * @param cityareaId the value for cityarea.cityArea_id
     *
     * @mbg.generated
     */
    public void setCityareaId(String cityareaId) {
        this.cityareaId = cityareaId == null ? null : cityareaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.cityArea_name
     *
     * @return the value of cityarea.cityArea_name
     *
     * @mbg.generated
     */
    public String getCityareaName() {
        return cityareaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.cityArea_name
     *
     * @param cityareaName the value for cityarea.cityArea_name
     *
     * @mbg.generated
     */
    public void setCityareaName(String cityareaName) {
        this.cityareaName = cityareaName == null ? null : cityareaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.city_id
     *
     * @return the value of cityarea.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.city_id
     *
     * @param cityId the value for cityarea.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }
}