package august.entity;

import java.util.Date;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_sex
     *
     * @mbg.generated
     */
    private String clientSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_password
     *
     * @mbg.generated
     */
    private String clientPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_phone
     *
     * @mbg.generated
     */
    private String clientPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_birthday
     *
     * @mbg.generated
     */
    private Date clientBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_site
     *
     * @mbg.generated
     */
    private String clientSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_remark
     *
     * @mbg.generated
     */
    private String clientRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_id
     *
     * @return the value of client.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_id
     *
     * @param clientId the value for client.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_name
     *
     * @return the value of client.client_name
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_name
     *
     * @param clientName the value for client.client_name
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_sex
     *
     * @return the value of client.client_sex
     *
     * @mbg.generated
     */
    public String getClientSex() {
        return clientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_sex
     *
     * @param clientSex the value for client.client_sex
     *
     * @mbg.generated
     */
    public void setClientSex(String clientSex) {
        this.clientSex = clientSex == null ? null : clientSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.user_id
     *
     * @return the value of client.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.user_id
     *
     * @param userId the value for client.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_password
     *
     * @return the value of client.client_password
     *
     * @mbg.generated
     */
    public String getClientPassword() {
        return clientPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_password
     *
     * @param clientPassword the value for client.client_password
     *
     * @mbg.generated
     */
    public void setClientPassword(String clientPassword) {
        this.clientPassword = clientPassword == null ? null : clientPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_phone
     *
     * @return the value of client.client_phone
     *
     * @mbg.generated
     */
    public String getClientPhone() {
        return clientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_phone
     *
     * @param clientPhone the value for client.client_phone
     *
     * @mbg.generated
     */
    public void setClientPhone(String clientPhone) {
        this.clientPhone = clientPhone == null ? null : clientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_birthday
     *
     * @return the value of client.client_birthday
     *
     * @mbg.generated
     */
    public Date getClientBirthday() {
        return clientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_birthday
     *
     * @param clientBirthday the value for client.client_birthday
     *
     * @mbg.generated
     */
    public void setClientBirthday(Date clientBirthday) {
        this.clientBirthday = clientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_site
     *
     * @return the value of client.client_site
     *
     * @mbg.generated
     */
    public String getClientSite() {
        return clientSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_site
     *
     * @param clientSite the value for client.client_site
     *
     * @mbg.generated
     */
    public void setClientSite(String clientSite) {
        this.clientSite = clientSite == null ? null : clientSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_remark
     *
     * @return the value of client.client_remark
     *
     * @mbg.generated
     */
    public String getClientRemark() {
        return clientRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_remark
     *
     * @param clientRemark the value for client.client_remark
     *
     * @mbg.generated
     */
    public void setClientRemark(String clientRemark) {
        this.clientRemark = clientRemark == null ? null : clientRemark.trim();
    }
}