package august.entity;

import java.util.Date;

public class Deliveryreceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.d_startcity
     *
     * @mbg.generated
     */
    private String dStartcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.d_destinationcity
     *
     * @mbg.generated
     */
    private String dDestinationcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.d_arrivedcity
     *
     * @mbg.generated
     */
    private String dArrivedcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.d_status
     *
     * @mbg.generated
     */
    private Integer dStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.d_createtime
     *
     * @mbg.generated
     */
    private Date dCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.d_remark
     *
     * @mbg.generated
     */
    private String dRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.d_startcity
     *
     * @return the value of deliveryreceipt.d_startcity
     *
     * @mbg.generated
     */
    public String getdStartcity() {
        return dStartcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.d_startcity
     *
     * @param dStartcity the value for deliveryreceipt.d_startcity
     *
     * @mbg.generated
     */
    public void setdStartcity(String dStartcity) {
        this.dStartcity = dStartcity == null ? null : dStartcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.d_destinationcity
     *
     * @return the value of deliveryreceipt.d_destinationcity
     *
     * @mbg.generated
     */
    public String getdDestinationcity() {
        return dDestinationcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.d_destinationcity
     *
     * @param dDestinationcity the value for deliveryreceipt.d_destinationcity
     *
     * @mbg.generated
     */
    public void setdDestinationcity(String dDestinationcity) {
        this.dDestinationcity = dDestinationcity == null ? null : dDestinationcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.d_arrivedcity
     *
     * @return the value of deliveryreceipt.d_arrivedcity
     *
     * @mbg.generated
     */
    public String getdArrivedcity() {
        return dArrivedcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.d_arrivedcity
     *
     * @param dArrivedcity the value for deliveryreceipt.d_arrivedcity
     *
     * @mbg.generated
     */
    public void setdArrivedcity(String dArrivedcity) {
        this.dArrivedcity = dArrivedcity == null ? null : dArrivedcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.d_status
     *
     * @return the value of deliveryreceipt.d_status
     *
     * @mbg.generated
     */
    public Integer getdStatus() {
        return dStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.d_status
     *
     * @param dStatus the value for deliveryreceipt.d_status
     *
     * @mbg.generated
     */
    public void setdStatus(Integer dStatus) {
        this.dStatus = dStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.d_createtime
     *
     * @return the value of deliveryreceipt.d_createtime
     *
     * @mbg.generated
     */
    public Date getdCreatetime() {
        return dCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.d_createtime
     *
     * @param dCreatetime the value for deliveryreceipt.d_createtime
     *
     * @mbg.generated
     */
    public void setdCreatetime(Date dCreatetime) {
        this.dCreatetime = dCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.d_remark
     *
     * @return the value of deliveryreceipt.d_remark
     *
     * @mbg.generated
     */
    public String getdRemark() {
        return dRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.d_remark
     *
     * @param dRemark the value for deliveryreceipt.d_remark
     *
     * @mbg.generated
     */
    public void setdRemark(String dRemark) {
        this.dRemark = dRemark == null ? null : dRemark.trim();
    }
}