package august.entity;

public class Line {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_id
     *
     * @mbg.generated
     */
    private String lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_name
     *
     * @mbg.generated
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.d_startcityId
     *
     * @mbg.generated
     */
    private String dStartcityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.d_startcity
     *
     * @mbg.generated
     */
    private String dStartcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.d_arrivedcity
     *
     * @mbg.generated
     */
    private String dArrivedcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.d_arrivedcityId
     *
     * @mbg.generated
     */
    private String dArrivedcityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.d_destinationcity
     *
     * @mbg.generated
     */
    private String dDestinationcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.d_destinationcityId
     *
     * @mbg.generated
     */
    private String dDestinationcityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_carriageprice
     *
     * @mbg.generated
     */
    private Long lineCarriageprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_remark
     *
     * @mbg.generated
     */
    private String lineRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_id
     *
     * @return the value of line.line_id
     *
     * @mbg.generated
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_id
     *
     * @param lineId the value for line.line_id
     *
     * @mbg.generated
     */
    public void setLineId(String lineId) {
        this.lineId = lineId == null ? null : lineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_name
     *
     * @return the value of line.line_name
     *
     * @mbg.generated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_name
     *
     * @param lineName the value for line.line_name
     *
     * @mbg.generated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName == null ? null : lineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.d_startcityId
     *
     * @return the value of line.d_startcityId
     *
     * @mbg.generated
     */
    public String getdStartcityid() {
        return dStartcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.d_startcityId
     *
     * @param dStartcityid the value for line.d_startcityId
     *
     * @mbg.generated
     */
    public void setdStartcityid(String dStartcityid) {
        this.dStartcityid = dStartcityid == null ? null : dStartcityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.d_startcity
     *
     * @return the value of line.d_startcity
     *
     * @mbg.generated
     */
    public String getdStartcity() {
        return dStartcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.d_startcity
     *
     * @param dStartcity the value for line.d_startcity
     *
     * @mbg.generated
     */
    public void setdStartcity(String dStartcity) {
        this.dStartcity = dStartcity == null ? null : dStartcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.d_arrivedcity
     *
     * @return the value of line.d_arrivedcity
     *
     * @mbg.generated
     */
    public String getdArrivedcity() {
        return dArrivedcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.d_arrivedcity
     *
     * @param dArrivedcity the value for line.d_arrivedcity
     *
     * @mbg.generated
     */
    public void setdArrivedcity(String dArrivedcity) {
        this.dArrivedcity = dArrivedcity == null ? null : dArrivedcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.d_arrivedcityId
     *
     * @return the value of line.d_arrivedcityId
     *
     * @mbg.generated
     */
    public String getdArrivedcityid() {
        return dArrivedcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.d_arrivedcityId
     *
     * @param dArrivedcityid the value for line.d_arrivedcityId
     *
     * @mbg.generated
     */
    public void setdArrivedcityid(String dArrivedcityid) {
        this.dArrivedcityid = dArrivedcityid == null ? null : dArrivedcityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.d_destinationcity
     *
     * @return the value of line.d_destinationcity
     *
     * @mbg.generated
     */
    public String getdDestinationcity() {
        return dDestinationcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.d_destinationcity
     *
     * @param dDestinationcity the value for line.d_destinationcity
     *
     * @mbg.generated
     */
    public void setdDestinationcity(String dDestinationcity) {
        this.dDestinationcity = dDestinationcity == null ? null : dDestinationcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.d_destinationcityId
     *
     * @return the value of line.d_destinationcityId
     *
     * @mbg.generated
     */
    public String getdDestinationcityid() {
        return dDestinationcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.d_destinationcityId
     *
     * @param dDestinationcityid the value for line.d_destinationcityId
     *
     * @mbg.generated
     */
    public void setdDestinationcityid(String dDestinationcityid) {
        this.dDestinationcityid = dDestinationcityid == null ? null : dDestinationcityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_carriageprice
     *
     * @return the value of line.line_carriageprice
     *
     * @mbg.generated
     */
    public Long getLineCarriageprice() {
        return lineCarriageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_carriageprice
     *
     * @param lineCarriageprice the value for line.line_carriageprice
     *
     * @mbg.generated
     */
    public void setLineCarriageprice(Long lineCarriageprice) {
        this.lineCarriageprice = lineCarriageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_remark
     *
     * @return the value of line.line_remark
     *
     * @mbg.generated
     */
    public String getLineRemark() {
        return lineRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_remark
     *
     * @param lineRemark the value for line.line_remark
     *
     * @mbg.generated
     */
    public void setLineRemark(String lineRemark) {
        this.lineRemark = lineRemark == null ? null : lineRemark.trim();
    }
}