package august.entity;

public class Orderlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_type
     *
     * @mbg.generated
     */
    private Integer oType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_number
     *
     * @mbg.generated
     */
    private String oNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_name
     *
     * @mbg.generated
     */
    private String oName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_weight
     *
     * @mbg.generated
     */
    private Integer oWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_sender
     *
     * @mbg.generated
     */
    private String oSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_start
     *
     * @mbg.generated
     */
    private String oStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_destination
     *
     * @mbg.generated
     */
    private String oDestination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_status
     *
     * @mbg.generated
     */
    private Integer oStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.senderphone
     *
     * @mbg.generated
     */
    private String senderphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.consigneephone
     *
     * @mbg.generated
     */
    private String consigneephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.startcity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.midpointcity
     *
     * @mbg.generated
     */
    private String midpointcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.destinationcity
     *
     * @mbg.generated
     */
    private String destinationcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.transportprice
     *
     * @mbg.generated
     */
    private Long transportprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.distributionprice
     *
     * @mbg.generated
     */
    private Long distributionprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.carriageprice
     *
     * @mbg.generated
     */
    private Long carriageprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.totalprice
     *
     * @mbg.generated
     */
    private String totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.car
     *
     * @mbg.generated
     */
    private String car;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.o_remark
     *
     * @mbg.generated
     */
    private String oRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_id
     *
     * @return the value of orderlist.o_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_id
     *
     * @param oId the value for orderlist.o_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_type
     *
     * @return the value of orderlist.o_type
     *
     * @mbg.generated
     */
    public Integer getoType() {
        return oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_type
     *
     * @param oType the value for orderlist.o_type
     *
     * @mbg.generated
     */
    public void setoType(Integer oType) {
        this.oType = oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_number
     *
     * @return the value of orderlist.o_number
     *
     * @mbg.generated
     */
    public String getoNumber() {
        return oNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_number
     *
     * @param oNumber the value for orderlist.o_number
     *
     * @mbg.generated
     */
    public void setoNumber(String oNumber) {
        this.oNumber = oNumber == null ? null : oNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_name
     *
     * @return the value of orderlist.o_name
     *
     * @mbg.generated
     */
    public String getoName() {
        return oName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_name
     *
     * @param oName the value for orderlist.o_name
     *
     * @mbg.generated
     */
    public void setoName(String oName) {
        this.oName = oName == null ? null : oName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_weight
     *
     * @return the value of orderlist.o_weight
     *
     * @mbg.generated
     */
    public Integer getoWeight() {
        return oWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_weight
     *
     * @param oWeight the value for orderlist.o_weight
     *
     * @mbg.generated
     */
    public void setoWeight(Integer oWeight) {
        this.oWeight = oWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_sender
     *
     * @return the value of orderlist.o_sender
     *
     * @mbg.generated
     */
    public String getoSender() {
        return oSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_sender
     *
     * @param oSender the value for orderlist.o_sender
     *
     * @mbg.generated
     */
    public void setoSender(String oSender) {
        this.oSender = oSender == null ? null : oSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_start
     *
     * @return the value of orderlist.o_start
     *
     * @mbg.generated
     */
    public String getoStart() {
        return oStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_start
     *
     * @param oStart the value for orderlist.o_start
     *
     * @mbg.generated
     */
    public void setoStart(String oStart) {
        this.oStart = oStart == null ? null : oStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_destination
     *
     * @return the value of orderlist.o_destination
     *
     * @mbg.generated
     */
    public String getoDestination() {
        return oDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_destination
     *
     * @param oDestination the value for orderlist.o_destination
     *
     * @mbg.generated
     */
    public void setoDestination(String oDestination) {
        this.oDestination = oDestination == null ? null : oDestination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_status
     *
     * @return the value of orderlist.o_status
     *
     * @mbg.generated
     */
    public Integer getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_status
     *
     * @param oStatus the value for orderlist.o_status
     *
     * @mbg.generated
     */
    public void setoStatus(Integer oStatus) {
        this.oStatus = oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.senderphone
     *
     * @return the value of orderlist.senderphone
     *
     * @mbg.generated
     */
    public String getSenderphone() {
        return senderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.senderphone
     *
     * @param senderphone the value for orderlist.senderphone
     *
     * @mbg.generated
     */
    public void setSenderphone(String senderphone) {
        this.senderphone = senderphone == null ? null : senderphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.consignee
     *
     * @return the value of orderlist.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.consignee
     *
     * @param consignee the value for orderlist.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.consigneephone
     *
     * @return the value of orderlist.consigneephone
     *
     * @mbg.generated
     */
    public String getConsigneephone() {
        return consigneephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.consigneephone
     *
     * @param consigneephone the value for orderlist.consigneephone
     *
     * @mbg.generated
     */
    public void setConsigneephone(String consigneephone) {
        this.consigneephone = consigneephone == null ? null : consigneephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.startcity
     *
     * @return the value of orderlist.startcity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.startcity
     *
     * @param startcity the value for orderlist.startcity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.midpointcity
     *
     * @return the value of orderlist.midpointcity
     *
     * @mbg.generated
     */
    public String getMidpointcity() {
        return midpointcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.midpointcity
     *
     * @param midpointcity the value for orderlist.midpointcity
     *
     * @mbg.generated
     */
    public void setMidpointcity(String midpointcity) {
        this.midpointcity = midpointcity == null ? null : midpointcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.destinationcity
     *
     * @return the value of orderlist.destinationcity
     *
     * @mbg.generated
     */
    public String getDestinationcity() {
        return destinationcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.destinationcity
     *
     * @param destinationcity the value for orderlist.destinationcity
     *
     * @mbg.generated
     */
    public void setDestinationcity(String destinationcity) {
        this.destinationcity = destinationcity == null ? null : destinationcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.transportprice
     *
     * @return the value of orderlist.transportprice
     *
     * @mbg.generated
     */
    public Long getTransportprice() {
        return transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.transportprice
     *
     * @param transportprice the value for orderlist.transportprice
     *
     * @mbg.generated
     */
    public void setTransportprice(Long transportprice) {
        this.transportprice = transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.distributionprice
     *
     * @return the value of orderlist.distributionprice
     *
     * @mbg.generated
     */
    public Long getDistributionprice() {
        return distributionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.distributionprice
     *
     * @param distributionprice the value for orderlist.distributionprice
     *
     * @mbg.generated
     */
    public void setDistributionprice(Long distributionprice) {
        this.distributionprice = distributionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.carriageprice
     *
     * @return the value of orderlist.carriageprice
     *
     * @mbg.generated
     */
    public Long getCarriageprice() {
        return carriageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.carriageprice
     *
     * @param carriageprice the value for orderlist.carriageprice
     *
     * @mbg.generated
     */
    public void setCarriageprice(Long carriageprice) {
        this.carriageprice = carriageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.totalprice
     *
     * @return the value of orderlist.totalprice
     *
     * @mbg.generated
     */
    public String getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.totalprice
     *
     * @param totalprice the value for orderlist.totalprice
     *
     * @mbg.generated
     */
    public void setTotalprice(String totalprice) {
        this.totalprice = totalprice == null ? null : totalprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.car
     *
     * @return the value of orderlist.car
     *
     * @mbg.generated
     */
    public String getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.car
     *
     * @param car the value for orderlist.car
     *
     * @mbg.generated
     */
    public void setCar(String car) {
        this.car = car == null ? null : car.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.o_remark
     *
     * @return the value of orderlist.o_remark
     *
     * @mbg.generated
     */
    public String getoRemark() {
        return oRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.o_remark
     *
     * @param oRemark the value for orderlist.o_remark
     *
     * @mbg.generated
     */
    public void setoRemark(String oRemark) {
        this.oRemark = oRemark == null ? null : oRemark.trim();
    }
}